- lib/deprecation_toolkit.rb
- lib/deprecation_toolkit/deprecation_subscriber.rb
- test/minitest/deprecation_toolkit_plugin_test.rb
- If the DeprecationSubscriber gets attached to the `rails` namespace
before the minitest plugin initialization kicks in, the gem would
attach the subscriber twice which would send 2 notifications per
deprecation.
Removed the testing isolation from the test as it was needed because
of this issue.
> Don't re-attach the subscriber if already attached:

- lib/deprecation_toolkit.rb
- test/minitest/deprecation_toolkit_plugin_test.rb
- If an app decide for some reason to attach namespace on the
subscriber before the minitest hook is triggered, we don't want to
reattach the same namespace on the subscriber again. Otherwise each
deprecations would trigger two warnings.
In #26, I made this change but this causes issue if a gem want to
attach multiple namespace to the subscriber.
Only the first namespace will be attached.
> Return earlier if Subscriber is already attached:

- CHANGELOG.md
- README.md
- lib/deprecation_toolkit/deprecation_subscriber.rb
- test/deprecation_toolkit/behaviors/raise_test.rb
- It's sometimes useful to allow some deprecations based on where they
get called from.
Imagine this kind of code:
```ruby
def foo
1000.times do
deprecation_call
end
end
def bar
deprecation_call
end
private
def deprecation_call
ActiveSupport::Deprecation.warn('Something')
end
```
Calling `foo`, will trigger a thousand deprecations that you'll to
record. You currently can whitelist the `Something` deprecation,
but if you do that will also ignore the deprecation that gets
triggered when calling `bar`.
If you want to fine grain, which deprecations should be allowed
based on the caller, then this PR allows you that.
The `Configuration.allowed_deprecations` now accepts procs. Procs
will be passed the deprecation message as well as the stacktrace.
Your proc needs to return a truthy value if the …
> Allow Procs inside the `Configuration.allowed_deprecations` array:

- CHANGELOG.md
- lib/deprecation_toolkit/behaviors/raise.rb
- lib/deprecation_toolkit/collector.rb
- test/deprecation_toolkit/behaviors/raise_test.rb
- test/deprecations/deprecation_toolkit/behaviors/raise_test.yml
- The error class triggered was, in some circumstances not the right
on (DeprecationRemoved instead of DeprecationIntroduced and vice
versa).
If the triggered deprecations were looking like `['C']` and the
recorded one like `['A', 'B']` it should have raised a
DeprecationRemoved error, but it was instead triggering a
DeprecationIntroduced one.
That situation was happening because we were comparing the recorded
deprecations agains the triggered one using the `<=>` operator
on arrays (Returns as soon as one element mismatch.)
Fix is to use the `<=>` operator on the Array's size instead.
> Fix issue where deprecation error raised could be incorrect:

- CHANGELOG.md
- lib/deprecation_toolkit/behaviors/raise.rb
- test/deprecation_toolkit/behaviors/raise_test.rb
- test/deprecations/deprecation_toolkit/behaviors/raise_test.yml
- If the number of triggered deprecations were the same as the number
of recorded one but they weren't matching the DeprecationToolkit
would have returned a `DeprecationRemoved` error. This is actually
misleading as it wasn't the case.
This PR introduces a `DeprecationMismatch` when this situation
happens.
> Introduce a new `DeprecationMismatch` error class:

- lib/deprecation_toolkit/warning.rb
Fixes #33 using the suggestion from https://github.com/rubygems/rubygems/issues/2588#issuecomment-452401326
We should prepend a module to patch Warning.warn because overriding the method directly assumes that no other code is patching Warning.warn as well as avoiding the assumption that Warning.warn is equivalent to Kernel.warn.
> Prepend module to Warning to patch Warning.warn

- CHANGELOG.md
- lib/deprecation_toolkit/collector.rb
- lib/deprecation_toolkit/minitest_hook.rb
- test/deprecation_toolkit/behaviors/raise_test.rb
- test/deprecations/deprecation_toolkit/behaviors/raise_test.yml
Add a way to mark a test as flaky:
- The deprecations triggered by some test is different (either they
get triggered in a different order or they don't trigger the same
amount of deprecations between multiple test runs).
By definition the test is flaky. Even if at the end the test passes,
the fact that sometime a method run and sometime it doesn't is the
sign of flakyness.
The deprecation toolkit can't deal with that.
This PR adds a way to mark a test as flaky so that the deprecations
triggered by the test will be ignored.
The syntax is like that:
```YAML
my_test:
- flaky: true
```
> Add a way to mark a test as flaky:

- .rspec
- .travis.yml
- Gemfile.lock
- README.md
- deprecation_toolkit.gemspec
- gemfiles/spec/deprecations/deprecation_toolkit/behaviors/raise.yml
- lib/deprecation_toolkit.rb
- lib/deprecation_toolkit/behaviors/ci_record_helper.rb
- lib/deprecation_toolkit/behaviors/raise.rb
- lib/deprecation_toolkit/behaviors/record.rb
- lib/deprecation_toolkit/configuration.rb
- lib/deprecation_toolkit/minitest_hook.rb
- lib/deprecation_toolkit/read_write_helper.rb
- lib/deprecation_toolkit/rspec.rb
- lib/deprecation_toolkit/rspec_plugin.rb
- lib/deprecation_toolkit/test_triggerer.rb
- spec/deprecation_toolkit/behaviors/disabled_spec.rb
- spec/deprecation_toolkit/behaviors/raise_spec.rb
- spec/deprecation_toolkit/behaviors/record_spec.rb
- spec/deprecations/deprecation_toolkit/behaviors/raise.yml
- spec/rspec/plugin_env_options_spec.rb
- spec/rspec/plugin_spec.rb
- spec/spec_helper.rb
- test/deprecation_toolkit/configuration_test.rb
This is a first pass at closing #17 by adding support for RSpec.
For Rspec users the setup is slightly different than minitest.
(In rails_helper.rb or spec_helper.rb)
```ruby
require 'deprecation_toolkit/rspec'
RSpec.configure do |config|
config.deprecation_behavior = :raise
end
```
Also it's worth noting that RSpec doesn't support adding custom flags when running tests. So you won't be able to add `--record-deprecations` when running your specs, but instead recording / raising  would have to be changed at the config level (like above).
For that I've made a small DSL so you can pass in a symbol of (`:raise`, `:record`, or :`disabled`).
I mostly want to open this PR to get some early feedback and see if this approach makes sense.  I still need to write some tests for this!
> Add rspec support

- lib/minitest/deprecation_toolkit_plugin.rb
- test/minitest/deprecation_toolkit_plugin_test.rb
Fix Minitest plugin kicking in when it shouldn't:
- When the deprecation toolkit get installed, it ends up in
somewhere in the GEM_PATH.
If you have a project that doesn't use bundler (like minitest itself),
then all minitest plugins found in the `GEM_PATH` will get loaded.
This is problematic because we don't want to run the deprecation_toolkit
on projects that didn't specify it.
This problem only happens on project not using bundler, because
otherwise, gems not part of the snapshots don't end up in the
load_path and thus the minitest plugin don't kick in.
> Fix Minitest plugin kicking in when it shouldn't:

- lib/deprecation_toolkit/warning.rb
- test/deprecation_toolkit/warning_test.rb
As explained in the code comments, that warning is sent in two part.
The problem is that if you raise on the first or second part, the warning becomes very hard to understand and deal with, so it's preferable to join the two parts together and consider them as a single warning.
> Handle multipart warnings

- README.md
It didn't seem obvious how to do this without looking at the source and another repo.
> [docs] Illustrate how to match all warnings

- lib/deprecation_toolkit.rb
When using the toolkit outside of Rails against MiniTest users will
receive the following error:
```
deprecation_toolkit/lib/deprecation_toolkit.rb:20:in
`add_notify_behavior': uninitialized constant
ActiveSupport::Deprecation (NameError)
```
This will raise even when not using `ActiveSupport::Deprecation` (i.e.
`warn 'Deprecated: this is my deprecation'`) as all deprecations are
then passed through `ActiveSupport::Deprecation` in the gem.
This PR requires the ActiveSupport dependency if not already defined to
cover off these cases.
Signed-off-by: Nick Schwaderer <nschwaderer@chef.io>
> Ensures ActiveSupport is required

- CHANGELOG.md
- Gemfile.lock
- RELEASE.md
- lib/deprecation_toolkit/version.rb
This PR updates the gem version to 2.0.0 ahead of release.
It also adds release notes, since there weren't any, and incidentally bumps the development version of `activesupport` (due to running `bundle install`) by one security patch version.
As per release instructions...
> Prepare 2.0.0 for release

- .github/workflows/ci.yml
We can rely on `TargetRubyVersion` to check the compatibility across Ruby versions. Rubocop isn't a runtime dependency, so we don't need to re-run the Rubocop check across Ruby and Active Support versions.
Spin off from #72
> Only run Rubocop once in CI

- .github/workflows/ci.yml
- Gemfile.lock
- deprecation_toolkit.gemspec
- lib/deprecation_toolkit/read_write_helper.rb
- test/deprecation_toolkit/behaviors/record_test.rb
When recording deprecations, a test case may have methods that are defined in other modules (eg. shared tests). When passing the test location to the proc deprecation_path, use the test case location instead to infer shred tests should be deprecated on the host test case.
> Use test case location to record deprecations

- lib/deprecation_toolkit/behaviors/raise.rb
- test/deprecation_toolkit/behaviors/raise_test.rb
- test/deprecations/deprecation_toolkit/behaviors/raise_test.yml
See: https://discourse.shopify.io/t/mistmatched-deprecations-between-spin-and-buildkite/35884
Output is confusing right now because although the diff is between the deprecation _without_ the stacktrace, the message shows it _with_ the stacktrace.
> Show deprecations without stacktrace

- CHANGELOG.md
- Gemfile.lock
- lib/deprecation_toolkit/version.rb
Releases https://github.com/Shopify/deprecation_toolkit/pull/78
> Prepare for 2.0.2 release

- lib/deprecation_toolkit/collector.rb
- test/deprecation_toolkit/behaviors/record_test.rb
[`Gem::Deprecate`](https://ruby-doc.org/3.2.0/stdlibs/rubygems/Gem/Deprecate.html) is a Ruby module that
> Provides 3 methods for declaring when something is going away.
Similarly to `ActiveSupport::Deprecation`, it generates warning messages, but with a different format:
```rb
class Foo
extend Gem::Deprecate
def old_method; end
deprecate :old_method, :new_method, 2019, 1
end
Foo.new.old_method
```
`deprecation_toolkit` strips out stack traces from deprecation warnings when recording them:
https://github.com/Shopify/deprecation_toolkit/blob/ee55e609e8b8f943d206b780e1a45d1347c40974/lib/deprecation_toolkit/behaviors/record.rb#L11
https://github.com/Shopify/deprecation_toolkit/blob/ee55e609e8b8f943d206b780e1a45d1347c40974/lib/deprecation_toolkit/collector.rb#L36-L44
There are multiple …
> Filter out stack trace from Gem::Deprecate deprecation messages

- .github/workflows/ci.yml
With the minimum ruby version of 3.1 CI was failing for edge on ruby 2.7 and ruby 3.0. This PR excludes those from CI. Also removes an old exclude for a ruby version not in the matric
> Exclude ruby 2.7 and 3.0 from CI

- CHANGELOG.md
- README.md
- lib/deprecation_toolkit/configuration.rb
- lib/deprecation_toolkit/read_write_helper.rb
- test/deprecation_toolkit/behaviors/record_test.rb
Currently, deprecation toolkit uses `class.name.underscore` to name the files where it stores the deprecations, which works well in most cases, but means that in the case of subclasses in test files (or typos), the actual files containing the deprecations are hard to find.
This allows the user to configure the file path/name format for their setup. It would allow folks to use the full file paths if that's easier for them and customize in any way that suits while maintaining the current behaviour as the default.
> Allow configuration of minitest file paths and file names

- CHANGELOG.md
- lib/deprecation_toolkit/warning.rb
`warn` may accept a `category:` keyword argument.
> Fix `Warning.warn` signature

- Gemfile
- Gemfile.lock
- lib/deprecation_toolkit.rb
- lib/deprecation_toolkit/deprecation_subscriber.rb
- lib/minitest/deprecation_toolkit_plugin.rb
- test/deprecation_toolkit/deprecation_subscriber_test.rb
- test/deprecation_toolkit/deprecation_toolkit_test.rb
- test/minitest/deprecation_toolkit_plugin_test.rb
Before, when the minitest plugin was used, the `attach_to` method of the `DeprecationSubscriber` class was called first only with the default set of gems to subscribe, which was `[:rails]`.
If the app added more gems to the `Configuration.attach_to` array, the `attach_subscriber` method was called again with the new gems, but this time, the `already_attached_to?` would return `true` since there was already a notifier in the subscriber.
We should check the subscribers instead and make sure we don't attach again to the same namespace.
> Allow deprecation toolkit to be attached to multiple gems

- lib/deprecation_toolkit/read_write_helper.rb
TLDR: Introduce `.sort.to_h` on write.
A common issue with using the deprecation toolkit in large organizations is that new faults are appended to the end of the file, which in a collaborative environment, can cause unnecessary merge conflicts.
By implementing `.sort.to_h`, we can ensure that deprecations are organized in a predictable manner. This reduces merge conflicts by aligning the order of the deprecations with the order of the original test file.
Additionally, I've revised the write method to prevent unnecessary file system creation, updates, and deletions where not required.
Lastly, I've incorporated logic to prevent file updates when the original and updated content are logically equivalent. In the context of an existing project, reordering the YAML content with .sort.to_h can …
> Stable write logic
